export enum ClientImportFileReason {
  MISSING = 'MISSING',
  TOO_LARGE = 'TOO_LARGE',
  UNSUPPORTED_TYPE = 'UNSUPPORTED_TYPE',
  CORRUPT = 'CORRUPT',
  MISSING_COLUMNS = 'MISSING_COLUMNS',
  EMPTY = 'EMPTY',
  TOO_MANY_ROWS = 'TOO_MANY_ROWS',
}
