export enum ServicesAnalyticsWidgetKey {
  SERVICES_COMPLETED_COUNT = 'SERVICES_COMPLETED_COUNT',
  REVENUE_PER_HOUR = 'REVENUE_PER_HOUR',
  SERVICES_DEMAND_BREAKDOWN = 'SERVICES_DEMAND_BREAKDOWN',
}
