-- AlterEnum
ALTER TYPE "AuditEvent" ADD VALUE 'SERVICE_CATEGORY_CREATED';
ALTER TYPE "AuditEvent" ADD VALUE 'SERVICE_CATEGORY_UPDATED';
ALTER TYPE "AuditEvent" ADD VALUE 'SERVICE_CATEGORY_DELETED';
ALTER TYPE "AuditEvent" ADD VALUE 'SERVICE_BUNDLE_CREATED';
ALTER TYPE "AuditEvent" ADD VALUE 'SERVICE_BUNDLE_UPDATED';
ALTER TYPE "AuditEvent" ADD VALUE 'SERVICE_BUNDLE_DELETED';
